before_install:
   - sudo apt-get update -qq
   - sudo apt-get install avahi-daemon libavahi-compat-libdnssd-dev
   - wget https://github.com/rebar/rebar/wiki/rebar
   - chmod u+x ./rebar
language: erlang
otp_release:
   - 17.5
   - 18.0
script: "./rebar compile && ./rebar ct skip_deps=true"
after_failure: "cat logs/raw.log"
